name: Chore Task
description: Track maintenance, cleanup, or technical tasks
title: "[Chore]: "
labels: ["chore"]
body:
  - type: markdown
    attributes:
      value: |
        Use this template for maintenance tasks, code cleanup, dependency updates, or other technical chores.
  
  - type: textarea
    id: task
    attributes:
      label: Task
      description: Describe the chore or maintenance task
      placeholder: What needs to be done?
    validations:
      required: true
  
  - type: textarea
    id: tech_details
    attributes:
      label: Technical Details
      description: Provide technical details, dependencies, or implementation notes
      placeholder: Include any technical information that would be helpful for completing this task...
    validations:
      required: false
